meshery-extensions/meshery-istio

CONTRIBUTING.md
README.md

Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

CONTRINUTING.md created

---

Dockerfile
go.mod
go.sum
istio/client.go
istio/install-istio.go
istio/istio.go
istio/vet.go
istio/yaml.go
main.go

The linting warnings are annoying, so this is an attempt at fixing them.

Fix lint - [WIP]

---

README.md

Added hyperlinks to badges on README, fixing #34 
Signed-off-by: Leandro Trovões <leandrotrovoes@hotmail.com>

Added hyperlinks to README badges

---

README.md

Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

#37 logo is updated

---

.github/ISSUE_TEMPLATE/documentation.md
.github/workflows/ci.yml

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added documentation.md

---

.github/ISSUE_TEMPLATE/documentation.md
.github/workflows/ci.yml
istio/client.go

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added package comment

---

.github/workflows/ci.yml
README.md

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added CII badge

---

.github/workflows/ci.yml

Fixes #66 
Signed-off-by: Naveen Jain nveenjain@gmail.com

Switch to Docker's GitHub Action

---

.github/workflows/ci.yml

Signed-off-by: Naveen Jain <nveenjain@gmail.com>

Update ci.yml to push to docker

---

istio/install-istio.go
istio/istio.go
istio/supported_ops.go

Fixes #36 (switching to istioctl as community moving from helm)
Signed-off-by: Naveen Jain <nveenjain@gmail.com>

Added support to install mTLS using istioctl

---

istio/install-istio.go
istio/istio.go
istio/supported_ops.go

Reverts layer5io/meshery-istio#69
Fixes #72

Revert "Added support to install mTLS using istioctl"

---

README.md

Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>
This PR fixes #1248

Update Meshery to Layer5

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Signed-off-by: Deborah <deborahemeni@gmail.com>

made changes to the .github folder

---

istio/client.go

temp fixes

---

Dockerfile
istio/client.go
istio/config_templates/addons/grafana.yaml
istio/config_templates/addons/jaeger.yaml
istio/config_templates/addons/prometheus.yaml
istio/config_templates/addons/zipkin.yaml
istio/config_templates/bookinfo-dr.yaml
istio/config_templates/mtls/deny-all.yaml
istio/config_templates/mtls/disable.yaml
istio/config_templates/mtls/permissive.yaml
istio/config_templates/mtls/strict.yaml
istio/install-istio.go
istio/istio.go
istio/supported_ops.go
scripts/install.sh

fixes for the adapter

---

istio/config_templates/imagehub-filter.yaml
istio/config_templates/imagehub-gateway.yaml
istio/config_templates/imagehub-patch.json
istio/config_templates/imagehub.yaml
istio/install-istio.go
istio/istio.go
istio/supported_ops.go

envoy filter

---

istio/istio.go
istio/supported_ops.go
scripts/delete.sh
scripts/deleteHttpbin.sh
scripts/install.sh

fixes for workshop

---

.github/workflows/release-drafter.yml

Use RELEASEDRAFTER_PAT instead of GH_Token

---

.github/workflows/ci.yml
go.mod

fixes for ci

---

Dockerfile
go.mod
go.sum
internal/config/config.go
internal/config/operations.go
istio/error.go
istio/install.go
istio/istio.go
istio/sample_apps.go
templates/bookinfo-gateway.yaml
templates/emojivoto-gateway.yaml
templates/httpbin-gateway.yaml
templates/imagehub-filter.yaml
templates/imagehub-gateway.yaml
templates/imagehub-patch.json
templates/policy-denyall.yaml
templates/policy-disable.yaml
templates/policy-mutual.yaml
templates/policy-strict.yaml

added policies, gateway resources and envoy filter

---

templates/imagehub-filter.yaml

changes proxy version

---

templates/imagehub-filter.yaml
templates/imagehub-gateway.yaml

changes for imagehub

---

istio/addons.go

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR fixes patch operations

Patch operation fix

---

README.md

Signed-off-by: Vi1234sh12 vishald41234@gmail.com
Update Image Path 
https://github.com/layer5io/layer5/blob/master/.github/assets/images/meshery/meshery-logo-tag-light-text-side.png

Update  Image Path  Meshery

---

templates/imagehub-filter.yaml
templates/imagehub-gateway.yaml
templates/imagehub-patch.json

fixes #195 
Signed-off-by: adpranavb2000@gmail.com <adpranavb2000@gmail.com>
This PR fixes #195, by adding webpage paths to the web-vs situated in imagehub-gateway.yaml.

added paths for web vs in image-hub sample app

---

Dockerfile

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR fixes #204

Update dockerfile to recursively copy templates

---

Dockerfile

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR fixes #207
**Relevant Screenshots**

Fix issue 207

---

go.mod
go.sum

Meshery Adapter Library Update to v0.1.18

---

README.md

Updated Community Section in Readme
This PR fixes #211 

Updated Community Section in Readme

---

go.mod
go.sum

Signed-off-by: leecalcote <leecalcote@gmail.com>

updating meshery-adapter-library

---

Makefile
component_info.json
errorutil_analyze_errors.json
errorutil_analyze_summary.json
errorutil_errors_export.json
internal/config/error.go
istio/error.go
istio/oam.go

Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR updates Errors to be Error Codes Utility Tool :hammer_and_wrench:  compatible.

Updated Errors to be Error Codes Utility Tool :hammer_and_wrench:  compatible 

---

.github/ISSUE_TEMPLATE/documentation.md
.github/config.yml
README.md

Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>
Changing layer5 link to meshery link
This PR also fixes #242 

Changing layer5 link to meshery link

---

istio/oam/register.go

This PR fixes #249 
changed /api/experimental/oam/workload to /api/oam/workload
changed /api/experimental/oam/trait to /api/oam/trait

changed istio apis

---

go.sum
internal/config/error.go
istio/error.go

Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR adds descriptions for the errors.
Still struggling with the tone of the error descriptions. Suggestions/comments for better descriptions are welcome.

Added error descriptions

---

internal/config/config.go

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
SMP protos compliant operation name for istio

SMP protos compliant operation name for istio

---

.gitignore
go.mod
go.sum
helpers/component_info.json
internal/config/error.go
istio/error.go
istio/install.go
istio/istio.go
istio/istio_test.go
istio/oam.go

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
* TODO: Fetch helm chart from downloaded istio tar

[lifecycle] Fix install operation

---

go.sum
internal/config/config.go
istio/istio.go
main.go

This PR fixes helm install issue. Moved back to viper while still being thread safe. Thanks to @kumarabd's thread safer viper implementation.

Fix Helm certificate issue

---

Dockerfile

This PR is a chore to update golang version in build stage. 
No, GitHub web doesn’t allow me to do so.

[CI] Upgrade golang version in Docker builder stage

---

.github/workflows/error-ref-publisher.yaml

Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>
Fix glob to match all required error.go files
Related to [this](https://github.com/meshery/meshery-istio/issues/267) issue

[CI] update pattern glob

---

Makefile

Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>
This PR fixes #63 

added make test

---

.github/workflows/ci.yml
Dockerfile

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>**Description**

[build] nodejs compatible base img

---

.github/label-commenter-config.yml
.github/workflows/label-commenter.yml

Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>
This PR fixes #276

add label commenter workflow

---

istio/install.go

Signed-off-by: aisuko <urakiny@gmail.com>
https://github.com/meshery/meshery-istio/pull/307#pullrequestreview-811775291

Fix the gosec-307

---

.github/workflows/update-oam-defs.yml

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
remove extra metdata from pre-generated components
This PR fixes #284 

removed extra metdata from pre-generated components

---

.github/workflows/slack.yml

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
It fixes the slack notification for new stargazers on this repo.

Slack notification

---

istio/addons.go

Avoid throwing error in case a patch doesn't exist

---

Dockerfile

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR is related to meshery/meshery#4642
WIP and requires suggestions...

[WIP] Bump version tags to fix CVEs

---

.github/workflows/slack.yml

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR makes the slack workflow consistent by using the env variable for the GitHub repo.
This PR fixes #314 

[Cl] Make Slack Workflow Consistent

---

.github/workflows/slack.yml

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
Fixes env variable for repo name

[Cl] Slack Workflow

---

.github/workflows/update-oam-defs.yml

Not having "title" field in oam_ref_schema breaks UI on meshmap as it relies on that field. This field is inserted in case of dynamic registeration, so with this PR, they would be added at build time as well.

Added title to oam_ref_schema

---

.github/workflows/ci.yml

Solved failing security checks

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Modify e2e wf

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Add signoff

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR fixes timestamp issue in e2e test results

Fix timestamp

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR fixes the SHA filename problem. Needs testing though!!!
Tests and checks needed in review

Fix symbols for filename (SHA)

---

main.go

Signed-off-by: leecalcote <leecalcote@gmail.com>

[Chore] misspelling of "adapter"

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Change format for date and SHA (for filenames)

---

.github/workflows/e2etest-servicemeshandaddon.yaml
.github/workflows/e2etest-servicemeshinstall.yaml

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
Hope this works... because it worked in linux shell

Edit date syntax to print with SHA

---

.github/workflows/e2etest-servicemeshandaddon.yaml

See https://github.com/meshery/meshery-istio/actions/runs/1634869405 as an example run of this proposed change.

[CI] Remove $ in e2e test workflow

---

main.go

- misspelling of "adapter"
- bind to localhost from mesherylocal.layer5.io
- move log message

[Chore] Move position and verbiage registration log message 

---

main.go

- misspelling of "adapter"
- bind to localhost from mesherylocal.layer5.io

[Lifecycle] Update default service bind address/hostname

---

.github/workflows/slack.yml

In this PR, I generalized the name of slack.yml workflow.
I missed this in my previous PR.

[Cl] Improve Name of Slack workflows

---

main.go

Change none to edge

---

.github/workflows/update-oam-defs.yml

Build components every day if new version available

---

.github/workflows/update.yaml

Adding mistypes signoff and branch

---

.github/workflows/update.yaml

Solve #362

---

main.go

Appropriate use of meshkit errors

---

.github/install/deploy.yaml
.github/install/deploywithaddons.yaml
go.mod
go.sum
istio/error.go
istio/install.go
istio/istio.go
istio/oam.go
templates/oam/workloads/istiomesh.meshery.layer5io.schema.json

Adding support for adding profile in Istio Mesh core component

---

.github/dependabot.yml

Remove Rudraksh from dependabot alerts

---

.github/dependabot.yml

Remove utkarsh from dependabot

---

Dockerfile

Signed-off-by: leecalcote <leecalcote@gmail.com>

[Chore] json utility update

---

.github/dependabot.yml
istio/error.go

Enhance errors

---

.github/install/deploywithsampleapp.yaml
.github/workflows/e2etests.yml

Implements E2E integration test with Istio service mesh and BookInfo sample app

[CI] E2E Test with sample app

---

istio/error.go

This PR also removes two of the errors popping up during the error code utility workflow.

Remove redudant error code

---

.github/workflows/e2etests.yml

Signed-off-by: Ruturaj Mohite <mohite.ruturaj15@gmail.com>
Ports the Istio to the new core e2e workflow
This PR is a part of https://github.com/meshery/meshery/issues/5529

[CI] Use updated core workflow for E2E

---

.github/workflows/e2etests.yml

Fixes docs generation for updated workflow in Istio.
Makes workflow run on push
Oversight in https://github.com/meshery/meshery-istio/pull/427. Please excuse my 1 am brain

[CI] Fix E2E Docs Generation

---

Dockerfile
go.mod
go.sum
istio/addons_test.go
istio/custom_operations_test.go
istio/istio.go

Final fix in multi cluster

---

istio/addons_test.go
istio/custom_operations_test.go
istio/istio_test.go

Fix failing vet checks

---

Dockerfile

Remove AMD hardcoding

---

Dockerfile

Remove kubeopenapi

---

go.mod
go.sum

Upgrade meshery adapter library

---

go.mod
go.sum

upgrade meshkit

---

go.mod
go.sum
istio/istio.go
istio/vet.go

Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
This PR enables sending complete error details to client;
1. Error Code
2. Cause 
3. Remedy
4. Component Type
5. Component Name
Dependent PR: https://github.com/meshery/meshery-adapter-library/pull/90

Send detailed error response to client

---

.github/install/deploywithsampleapp.yaml

fix sample app e2e tests

---

.github/workflows/e2etests.yml

Remove inter-dependency of updating docs

---

.github/config.yml

Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>
The welcome image for the 1st PR merge appears to be broken.
This PR fixes # The broken image by updating the link.

Updating the image for welcome of 1st PR merge 

---

Makefile
build/Makefile.core.mk

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

Relax Go version requirements

---

.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.github/workflows/component-generator.yaml
.github/workflows/components-to-doc.yml
.github/workflows/e2etests.yml
.github/workflows/error-ref-publisher.yaml
.github/workflows/label-commenter.yml
.github/workflows/multi-platform.yml
.github/workflows/release-drafter.yml
.github/workflows/slack.yml

Signed-off-by: Atharva Shirdhankar <ashirdhankar458@gmail.com>
This PR fixes https://github.com/meshery/meshery/issues/6666
In this PR I've updated github actions workflow which runs on ubuntu-latest to ubuntu-22.04 for meshery-istio

updated gh workflow from ubuntu-latest to ubuntu-22.04

---

build/config.go
build/meshmodel_metadata.json

Signed-off-by: Gopi Vaibhav <gopivaibhav0@gmail.com>
This PR fixes:
- Taking out the meshmodel metadata configuration from .go file to a JSON file for easier updation of Metadata.

Externalizing the config

---

.github/workflows/components-to-doc.yml

Signed-off-by: siddhikhapare <siddhikhapare66@bvcoenm.edu.in>

changed path of workflow

---

.github/workflows/build-and-release.yml
.github/workflows/newcomers-alert.yml
.github/workflows/slack.yml

This PR replicates the workflows setup from others adapters

[CI] Newcomers workflow propagation

---

istio/oam/register.go

[chore] fix lint failures

---

.github/config.yml

Add the line for asking users for starring the repository.
This PR fixes #568

Add the line for asking users for starring the repository.

---

istio/istio.go

add detailed msgs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md

Updating Figma Open Invite Link in Docs

---

.github/workflows/e2etests.yml

This PR is a part of meshery/meshery#12868

[WIP]:Changing Upload and download artifact actions to v4

---

.gemini/config.yaml

Signed-off-by: marblom007 <158522975+marblom007@users.noreply.github.com>

[CI] Disable Gemini

---

main.go

Update copyright in main.go

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/ci.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/config.yml
.github/label-commenter-config.yml
CONTRIBUTING.md
LICENSE
README.md
internal/config/error.go

Chore: Update config.yml
